### ISSUE TITLE
Green Background

### ISSUE THREAD

**Issue by Entonement** [Ploaj/SSBHLib#97] opened 2021-12-21 10:54 UTC
Hi, 

I tried to change the Background (Green) but it doesn't work even if I changed the value in ViewportRender.cs and rebuilt the project.
Is it normal ?

**Comment by Entonement** [comment] 2021-12-21 10:56
After Build I export the file SsbhLib.dll in the folder who contians a last release of crossmod

**Comment by ScanMountGoat** [comment] 2021-12-21 15:03
ViewportRenderer.cs is part of the CrossMod project, so you need to change CrossMod.dll.

**Comment by Entonement** [comment] 2021-12-21 15:21
Okay I will try it but when I build, there is only Ssbhlib.dll et SsbhBatchProcess.dll

**Comment by ScanMountGoat** [comment] 2022-01-09 04:38
I'm closing this since it's not a bug or feature request. Feel free to ask questions in this issue if you're still stuck.

**Closed by ScanMountGoat** 2022-01-09 04:38 UTC
